# Numpy

<a href="http://www.numpy.org/">Numpy</a> is the core library for scientific computing in Python. It provides a high-performnace multidimensional array object, and tools for working with these arrays.

## Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.
We can initialize numpy arrays from nested Python lists, and access elements using square brackets:
https://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
print(a.shape)

(3,)


In [4]:
print(a[0], a[1], a[2])

1 2 3


In [6]:
a[0] = 5
print(a)

[5 2 3]


In [7]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [8]:
print(b.shape)

(2, 3)


In [9]:
print(b[0,0], b[0,1], b[1,0])

1 2 4


#### Numpy also provides many functions to create arrays

In [18]:
a = np.zeros((2,2)) # create an array of all zeros
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [19]:
b = np.ones((1, 2)) # craete an array of all ones
print(b)

[[ 1.  1.]]


In [20]:
c = np.full((2,2), 7) # create a constanct array
print(c)

[[ 7.  7.]
 [ 7.  7.]]


/home/tianranchen/anaconda3/lib/python3.5/site-packages/numpy/core/numeric.py:294: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [21]:
d = np.eye(2) # create a 2x2 identify matrix
print(d)

[[ 1.  0.]
 [ 0.  1.]]


In [22]:
e = np.random.random((2,2)) # create an array filled with random values
print(e)

[[ 0.35549726  0.69430156]
 [ 0.4271774   0.54671924]]


## Array indexing
Numpy offers several ways to index into arrays
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

<b>Slicing:</b> Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array

In [27]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
"""
[[1  2  3  4]
 [5  6  7  8]
 [9 10 11 12]]
"""
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2
# b is the following array of shape(2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it will modify the original array
print(a[0, 1])
b[0,0] = 77
print(a[0, 1])

[[2 3]
 [6 7]]
2
77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing

In [29]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
"""
[[1  2  3  4]
 [5  6  7  8]
 [9 10 11 12]]
"""
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Two ways of accessing the data in the middle rows of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the original array

row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

# We can make the same distinction when accessing columns of an array
col_c1 = a[:, 1]
col_c2 = a[:, 1:2]
print(col_c1, col_c1.shape)
print(col_c2, col_c2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


<b>Integer array indexing:</b> When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array.

In [33]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])

# An example of integer array indexing
# The returned array will have shape (3,)
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0,0], a[1,1], a[2, 0]]))

# When using integer array indexing, you can resue the same element from the source array
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix 

In [37]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


<b>Boolean array indexing:</b> Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.

In [41]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])

bool_idx = (a > 2) # find the elements of a that are bigger than 2;
                   # this returns a numpy array of booleans of the same shape as a,
                   # where each slot of bool_idx tells whether that element of a is > 2
print(bool_idx)

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
