# Numpy

<a href="http://www.numpy.org/">Numpy</a> is the core library for scientific computing in Python. It provides a high-performnace multidimensional array object, and tools for working with these arrays.

## Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.
We can initialize numpy arrays from nested Python lists, and access elements using square brackets:
https://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation

In [3]:
import numpy as np
a = np.array([1, 2, 3])  # create a rank 1 array
print(type(a))

<class 'numpy.ndarray'>


In [3]:
print(a.shape)

(3,)


In [4]:
print(a[0], a[1], a[2])

1 2 3


In [6]:
a[0] = 5
print(a)

[5 2 3]


In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]]) # create a rank 2 array

In [5]:
print(b.shape)

(2, 3)


In [6]:
print(b[0,0], b[0,1], b[1,0])

1 2 4


#### Numpy also provides many functions to create arrays

In [18]:
a = np.zeros((2,2)) # create an array of all zeros
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [19]:
b = np.ones((1, 2)) # craete an array of all ones
print(b)

[[ 1.  1.]]


In [20]:
c = np.full((2,2), 7) # create a constanct array
print(c)

[[ 7.  7.]
 [ 7.  7.]]


/home/tianranchen/anaconda3/lib/python3.5/site-packages/numpy/core/numeric.py:294: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [21]:
d = np.eye(2) # create a 2x2 identify matrix
print(d)

[[ 1.  0.]
 [ 0.  1.]]


In [22]:
e = np.random.random((2,2)) # create an array filled with random values
print(e)

[[ 0.35549726  0.69430156]
 [ 0.4271774   0.54671924]]


## Array indexing
Numpy offers several ways to index into arrays
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

<b>Slicing:</b> Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array

In [27]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
"""
[[1  2  3  4]
 [5  6  7  8]
 [9 10 11 12]]
"""
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2
# b is the following array of shape(2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it will modify the original array
print(a[0, 1])
b[0,0] = 77
print(a[0, 1])

[[2 3]
 [6 7]]
2
77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing

In [29]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
"""
[[1  2  3  4]
 [5  6  7  8]
 [9 10 11 12]]
"""
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Two ways of accessing the data in the middle rows of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the original array

row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

# We can make the same distinction when accessing columns of an array
col_c1 = a[:, 1]
col_c2 = a[:, 1:2]
print(col_c1, col_c1.shape)
print(col_c2, col_c2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


<b>Integer array indexing:</b> When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array.

In [33]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])

# An example of integer array indexing
# The returned array will have shape (3,)
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0,0], a[1,1], a[2, 0]]))

# When using integer array indexing, you can resue the same element from the source array
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix 

In [37]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


<b>Boolean array indexing:</b> Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.

In [41]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])

bool_idx = (a > 2) # find the elements of a that are bigger than 2;
                   # this returns a numpy array of booleans of the same shape as a,
                   # where each slot of bool_idx tells whether that element of a is > 2
print(bool_idx)

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


## Datatypes 
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specily the datatype.
You can read all about numpy datatypes <a href="https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html"> in the documentation</a>

In [3]:
import numpy as np

x = np.array([1, 2])  # Let numpy choose the datatype
print(x.dtype)        # Prints "int64"

x = np.array([1.0, 2.0])  # Let numpy choose the datatype
print(x.dtype)            # Prints "float64"

x = np.array([1, 2], dtype=np.int64) # Force a particular datatype
print(x.dtype)                       # Prints "int64"

int64
float64
int64


## Array math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:
You can find the full list of mathematical functions provided by numpy <a herf="https://docs.scipy.org/doc/numpy/reference/routines.math.html">in the documentation</a>

In [7]:
import numpy as np

x = np.array([[1, 2],[3, 4]], dtype=np.float64)
y = np.array([[5, 6],[7, 8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[6.0  8.0]
#  [10.0  12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


Note that unlike MATLAB, <b>*</b> is elementwise multiplication, not matrix multiplication. We instead use the <b>dot</b> function to compute inner products of vectors, to multiply as vector by a matrix, and to multiply matrices. <b>dot</b> is available both as a function in the numpy module and as an instance method of array objects:

In [10]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# matrix / vector product; both produce the rank 1 array
print(x.dot(v))
print(np.dot(x, v))

# matrix / matrix product; both produce the rank 2 array
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is <b>sum</b>

In [18]:
import numpy as np

x = np.array([[1, 2], [3, 4]])

print(np.sum(x)) # compute the sum of all elements
print(np.sum(x, axis=0)) # compute the sum of each column
print(np.sum(x, axis=1)) # compute the sum of each row

10
[4 6]
[3 7]


## Broadcasting
<br/>
<font size="3">Broadcasting is powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.
For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:
</font>

In [8]:
import numpy as np

# we will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)  # create an empty matrix with the same shape as x

# add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


<font size="3"> This works; however when the matrix <b>x</b> is very large, computing an explicit loop in Python could be slow. Note that adding the vector <b>v</b> to each row of the matrix <b>x</b> is equivalent to forming a matrix <b>vv</b> by stacking multiple copies of <b>v</b> vertically, then performing elementwise summation of <b>x</b> and <b>vv</b>. We could implement this approach like this: </font>

In [9]:
import numpy as np

# we will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))  # stack 4 copies of v on top of each other 
print(vv)

y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


<font size="3">
Numpy broadcasting allows us to perform this computation without actually creating multiple copies of <b>v</b>.
Consider this version, using broadcasting:
</font>

In [10]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

y = x + v  # add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


<font size="3">
The line <b>y = x + v</b> works even though <b>x</b> has shape <b>(4, 3)</b> and <b>v</b> has shape <b>(3,)</b> due to broadcasting; this line works as if <b>v</b> actually had shape <b>(4, 3)</b>, where each row was a copy of <b>v</b>, and the sum was performed elementwise.
<br />
Broadcasting two arrays together follows these rules:
<ol> 
  <li>If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
  <li>The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
  <li>The arrays can be broadcasting together if they are compatible in all dimensions.
  <li>After broadcasting, each array behaves as if it had shape equal to the elelemntwise maximum of shapes of the two input arrays.
  <li>In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.
</ol>
If this explanation does not make sense, try reading the explanation from the <a href="https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html">documentation</a> or <a href="http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc">this explanation.</a> 
</font>

### Numpy Documentation

<font size="3">
This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the <a href="https://docs.scipy.org/doc/numpy/reference/">numpy reference</a> to find out much more about numpy.
</font>